[package]
name = "rubit-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rubit = { path = "../rubit" }
bencode = { path = "../bencode" }
url = "2.5.2"
sha1 = "0.10.6"
indicatif = "0.17.8"
rand = "0.8.5"
