[package]
name = "rubit"
version = "0.1.0"
edition = "2021"

[dependencies]
rubit-bencode = { path = "../rubit-bencode" }
rand = "0.8.5"
ureq = { version = "2.10.1", features = ["native-tls"] }
url = "2.5.2"
sha1 = "0.10.6"
indicatif = "0.17.8"
